# Introduction to Python
----

## Python Basics 
----
Python has a lot of uses, the most basic one is as a *Calculator*

In [ ]:
# Addition, subtraction
print(5 + 5)
print(5 - 5)

# Multiplication, division, modulo, and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

### Variables and Types
> A **variable** allow you to store a result or a value and re use it  
#### Most common types in Python
- Int (integer): a number without a fractional part
- Float (floating point): a number that has both an integer and fractional part, separated by a point  
- Str (string): a type to represent text. 
    >***Note:*** You can use *single* or *double* quotes to build a string
- Boolean: a type to represent logical values. Can only be ***True*** or ***False***

In [2]:
# To check the type of data that is stored in a variable
weight = 57.8
type(weight)

float

**Note:** The operators *behave differently* for different data types

In [9]:
print(2 + 3)
print('ab' + 'cd')
print("I said " + ("Hey " * 2) + "Hey!")
print(True + False)

5
abcd
I said Hey Hey Hey!
1


To convert a ***value*** into a ***string*** use **str()**
> Similar functions such as int(), float() and bool() will help you convert Python values into any type.

In [7]:
# Definition of variables
savings = 100
result = 100 * 1.10 ** 7

# Printout using the + operator
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)
print(type(pi_float))

I started with $100 and now have $194.87171000000012. Awesome!
<class 'float'>


## Python Lists
----
A list is a way to give a single name to a collection of values. The elements can have any type and contain diffent types (Lists can even contain lists themselves).

In [ ]:
# Lists can have elements of different types
fam1 = ['liz',1.73,'emma',1.68,'mom','1.71']

# Lists can contain lists
fam2 = [['liz',1.73],
        ['emma',1.68],
        ['mom','1.71']]

# List can contain variables previously set
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall,kit,liv,bed,bath]
    
# Print areas
print(areas)
print(type(areas))

### Subsetting lists

#### Indexing
To select an element from a list we use the *index* 
> - The first element in the list has index 0  
> - if we use negative numbers insted, we will select the last elements in the list



In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

In [ ]:
# Subset and calculate
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = (areas[3] + areas[-3])

# Print the variable eat_sleep_area
print(eat_sleep_area)

To subset ***lists of lists***, you can use the same technique as before: square brackets.

In [ ]:
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]
x[2][0]
x[2][:2]

# x[2] results in a list, that you can subset again by adding additional square brackets.

### List Slicing
Creating a new list by selecting some elements from an existing list.

This is the sintaxis for slicing
***[ start : end ]***

>The index that is set in the start ***will be included*** in the new list. The index that is set in the end is ***excluded***. 
> - If nothing is specified in the ***start***, elements will be selected starting from index 0
> - If nothing is specified in the ***end***, elements will be selected until the last item of the list

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to select first 6 elements
downstairs= areas[:6]

# Use slicing to select last 4 elements
upstairs = areas[6:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

### Manipulating Lists

#### Replace list elements
Subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once.

In [ ]:
x = ["a", "b", "c", "d"]

# To replace a single value from a list (result: ['a', 'r', 'c', 'd'])
x[1] = "r"

# To replace multiple elements from a list (result: ['a', 'r', 's', 't'])
x[2:] = ["s", "t"]

#### Extend a list
To add elements to a list use the + operator:

In [3]:
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]
print(y)

['a', 'b', 'c', 'd', 'e', 'f']


#### Delete list elements
To remove elements from a list you can use the ***del*** statement.

In [ ]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# To delete "poolhouse" and 24.5 we will use the following command
del(areas[-4:-2])

#The ; sign is used to place commands on the same line. The following two code chunks are equivalent:
del(areas[10]); del(areas[11])

del(areas[10]) 
del(areas[11])

#### Important consideration - Inner working of list
Consider the following example:

In [6]:
# Create list areas
areas = [11.25, 18.0, 20.57, 10.75, 9.50]

# Create areas_copy
areas_copy = areas

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[5.0, 18.0, 20.57, 10.75, 9.5]


In the previous example, the first element in the areas_copy list is changed and the areas list is printed out. Although you've changed areas_copy, the change also takes effect in the areas list. That's because ***areas and areas_copy point to the same list***.

If you want to prevent changes in areas_copy from also taking effect in areas, you'll have to do a more explicit copy of the areas list. You can do this with ***list()*** or by using ***[:]***.

## Functions and Packages
----


### Function
Piece of reusable code that solves a particular task. The result of a function can be asigned to a variable. The general recipe for calling functions and saving the result to a variable is thus:
> *output = function_name(input)*

In [17]:
# Examples of functions

# Print will print the result of the command or fuction executed.
print(areas)

# Max fuction will identify the max value.
biggest = max(areas)

# Type funtion will tell you the type of a variable.
print(type(areas))

# Round will round your result to the closest integer. The number of decimal can be adjusted in the second paramenter. 
var1 = round(biggest)
print(type(var1))

# str(), int(), bool() and float() let you to switch between data types.
print(type(str(var1)))

# Use len() to get the length of the list
print(len(areas))

# pow() let you calculate the power of a number

[5.0, 18.0, 20.57, 10.75, 9.5]
<class 'list'>
<class 'int'>
<class 'str'>
5


In [8]:
# Help can be use to check the documentation of a particular function
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [19]:
# Sorted Function:

# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full,reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


### Methods
Fuctions that belong to python objects.

| Object | type | Examples of Methods |
| ------ | ---- | ------- |
| 1 | str | capitalize() or replace() |  
| 2 | float | bit_lenght() or conjugate() |
| 3 | list | index() or count() |

In [33]:
# Example of methods in list 

# .index() will return the index of an specific element in a list
print(full_sorted)
print(full_sorted.index(18.0))

# .count() will return the number of times an element is present in a list
print(full_sorted.count(0))

# .append() will add a new element to a list in the last position
full_sorted.append('new')
print(full_sorted)

print(areas)
areas.append(24.5)
areas.append(15.45)

# remove(), that removes the first element of a list that matches the input

# reverse(), that reverses the order of the elements in the list it is called on.
print(areas)
areas.reverse()
print(areas)

# Note: All the methods for lists can be used on str

[20.0, 18.0, 11.25, 10.75, 9.5, 'new']
1
0
[20.0, 18.0, 11.25, 10.75, 9.5, 'new', 'new']
[5.0, 18.0, 20.57, 10.75, 9.5]
[5.0, 18.0, 20.57, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.57, 18.0, 5.0]


In [32]:
# Example of str methods

sister = 'liz'
print(sister) 

# .capitalize() will transform the first letter of the string into capital letter. 
sis1 = sister.capitalize() 
print(sis1)

# .replace() replace some parts of a string with other parts
sis2 = sister.replace('z','sa')
print(sis2)

# Use the upper() method to change all the letter to upper case
sis3 = sister.upper()
print(sis3)



liz
Liz
lisa
LIZ


### Packages
A directory of python scripts. Each script is called a module and it specifies functions, methods and types. There are a lot of packages available online, the most used for Data Science are: 
- Numpy: to work with arrays.
- Matpltlib: for data visualization.
- scikit-learn: for machine learning. 

To use the different packages they should be installed in our systems. Some IDE and environments have them available but to installed them directly in our local machine the following steps must be followed: 
1. Follow this [Link](https://pip.pypa.io/en/stable/installation/)
2. dowload the get-pip.py file
3. In the terminal run the following command: ```python3 get-pip.py```
4. Now, we can use pip to install any python package. Example: ```pip3 install numpy```

Now that the package is installed, it is usable in our python scripts by importing the whole package or an specific module of it. 

>To import the whole numpy package for example we will use ``` import numpy as np ```
>
>To use a function from the numpy package we will call it like this: ```np.array()```
>
> To import only one module from the numpy package ``` from numpy import array ```

In [38]:
# Import pi from math package to calculate the circunference and area

# Definition of radius
r = 0.43

# Import the math package
from math import pi, radians

# Calculate C
C = 2*pi*r 

# Calculate A
A = pi*pow(r,2)

# Calculate dist
dist = r*radians(12)

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))
print("Distance : " + str(dist))

Circumference: 2.701769682087222
Area: 0.5808804816487527
Distance : 0.09005898940290741


## Numpy
------

### Numpy (Numeric Python)
NumPy is a fundamental python package. It allows you to create Numpy Arrays to perform operations in lists. Considerations: 
>- A Numpy Array is a new type of python object so it has it's own methods associated to it
>- **All the elements** included in an NumPy Array need to be of the **same type** (int, str, float, bool, etc). This is known as *type coercion*.
>- The typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

To create a Numpy array you need to:

1. Import the Numpy package. 

``` Import numpy as np ```

2. The run the .array method.

```numpy_array = np.array(x,y,z) ```

In [3]:
# Example Numpy Array

# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

# Make calculation over the elements of a numpy array
np_baseball_meters = np_baseball / 100 
print(np_baseball_meters)

<class 'numpy.ndarray'>
[1.8  2.15 2.1  2.1  1.88 1.76 2.09 2.  ]


### Subsetting a numpy array
To subset both regular Python lists and numpy arrays, you can use square brackets

In [8]:
# Python List
x = [4 , 9 , 6, 3, 1]
print(x[1])

# Numpy Array
import numpy as np
y = np.array(x)
print(y[1])

# For numpy specifically, you can also use boolean numpy arrays
high = y > 5
print(y[high])

# Slicing. (Note: remember that the first index will be included the end index will not be included) 
print(x[2:4])

9
9
[9 6]
[6, 3]


### 2D Numpy Arrays

In [ ]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array([[180, 78.4],[215, 102.7],[210, 98.5],[188, 75.2]])
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball 
print(np_baseball.shape)
# (Note: shape gives extra information on the arrays. Shape is an attribute. Attributes are different from methods) 

#### Subsetting 2D NumPy Arrays

In [ ]:
# regular list of lists
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

# numpy
import numpy as np
np_x = np.array(x)
np_x[:, 0]

The indexes before the comma refer to the rows, while those after the comma refer to the columns. The : is for slicing; in this example, it tells Python to include all rows.

#### 2D Arithmetic

In [2]:
import numpy as np

np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

# To multiply all the element in an array by a number
print(np_mat * 2)

# The following code with add 10 to all elements in the fisrt column and 5 to all elements in second 
print(np_mat + np.array([10, 5]))

# to add 2 arrays
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[11  7]
 [13  9]
 [15 11]]
[[ 2  4]
 [ 6  8]
 [10 12]]


### NumPy: Basic Statistics

In [3]:
import numpy as np

x = [1, 4, 8, 10, 12]

# Calculate the mean np.mean()
print(np.mean(x))

# Calculate the median np.median()
print(np.median(x))

# Calculate the correlation np.corrcoef() 

# Calculate the standard deviation np.std()
print(np.std(x))

7.0
8.0
4.0
